FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -yq firefox
CMD ["firefox", "https://www.youtube.com/watch?v=X_kYPLoOZE8"]

#xhost+
#sudo docker image build -t ff_test .
#docker run -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix f_test
